# Properties migrator demo
Spring Boot 2 introduced a new feature that allows to inspect the `Environment` on startup
and give a report of properties usage that are no longer supported.

Properties that can be migrated automatically are migrated at runtime with a `warning`
report that lists the properties and their replacements so that you can adapt your
configuration.

Properties that have no replacement or not a one-to-one replacement (e.g. a property that
was split in two or several properties that were combined into one) are listed in an
`error` report with some further information.

To enable the report during the migration, simply add an extra module to your project

[source,xml]
----
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-properties-migrator</artifactId>
	<scope>runtime</scope>
</dependency>
----

Or if you're using Gradle:

[source]
----
runtime("org.springframework.boot:spring-boot-properties-migrator")
----

All the behaviour of the tool is derived from the metadata which means custom starters
and application configuration can also be migrated the exact same way. This sample project
showcase different use cases, each in its own commit.

# Steps

## Simple App
Initially, we have a simple `1.5.` app with several properties used to customize things.
Not all of them are relevant to this app and have been added solely to demonstrate the
migration.

The important piece is that the actuator is running on port 9090 and the `health` endpoint
has been customized and is available at `http://localhost:9090/my-health` rather than
`http://localhost:9090/health`.

## Upgrade App to Spring Boot 2
If we upgrade the application to Spring Boot, we noticed that properties defined in
`application.properties` show up as errors. That's because those keys have changed and
are no longer honoured.

If we start our app now, we can see that the health endpoint is available at
`http://localhost:8080/actuator/health` (as the default context for actuator endpoints is
`/actuator` rather than `/` in Spring Boot 2).

The assistance in the IDE is very nice but not all properties are accessible from it. In
the next step we'll add the migrator.

## Add Properties Migrator
If we add `spring-boot-properties-migrator` to the app, the migration kicks in
automatically and report the following on startup:

[source]
----
2018-08-29 09:54:28.497  WARN 77310 --- [           main] o.s.b.c.p.m.PropertiesMigrationListener  :
The use of configuration keys that have been renamed was found in the environment:

Property source 'applicationConfig: [classpath:/application.properties]':
	Key: endpoints.health.path
		Line: 6
		Replacement: management.endpoints.web.path-mapping.health
	Key: management.port
		Line: 3
		Replacement: management.server.port


Each configuration key has been temporarily mapped to its replacement for your convenience. To silence this warning, please update your configuration to use the new keys.

2018-08-29 09:54:28.498 ERROR 77310 --- [           main] o.s.b.c.p.m.PropertiesMigrationListener  :
The use of configuration keys that are no longer supported was found in the environment:

Property source 'applicationConfig: [classpath:/application.properties]':
	Key: management.security.enabled
		Line: 4
		Reason: A global security auto-configuration is now provided.
	Key: security.basic.enabled
		Line: 1
		Reason: The security auto-configuration is no longer customizable.


Please refer to the migration guide or reference guide for potential alternatives.
----

The first report warns us about two properties that could be migrated at runtime and still
require the source to be updated. The health endpoint is now back at
`http://localhost:9090/actuator/my-health`.

There are two keys (unused and for demonstration purposes) that are no longer used and for
which there isn't a replacement. Some dedicated actions are required.

## Fix Configuration
We can now fix configuration based on the advice. If we restart the application, the
report doesn't show anything particular.

That does not explain how you can use the properties migration with your own keys. Let's
initiate that in the next step.

## Add Simple Library
A new project called `demo-properties-migrator-lib` showcases a very simple custom
auto-configuration that exposes two keys: `demo.acme.name` and `demo.acme.counter`. We're
now using this library in our project that outputs the following on startup:

[source]
----

Value for name: 'my-test'

----

 